apiVersion: v1
kind: Service
metadata:
  name: &service-name docker-k8s-walkthrough
spec:
  type: NodePort
  selector:
    app: *service-name
  ports:
    - name: http
      port: 10000
      nodePort: 30900 # nodePort has to be in range 30000-32767
      protocol: TCP